title: Optiplan
description: Büro für Gebäude- und Installationstechnik

url: "https://gryphiusodenhobler.github.io"
baseurl: "/www.optiplan.at"

locale: "de-AT"

minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache

footer:
  links: []

atom_feed:
  hide: true
  
